name = "LennardJones"
uuid = "f59c176c-0be3-4f9d-8d5a-ab7c38a790ce"
authors = ["Hitoshi Wako <Hitoshi.Wako@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
